import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import glob
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# ============================================================================
# CONFIGURATION & FILE DISCOVERY
# ============================================================================
# This matches the folder structure generated by your analysis script
ANALYSIS_OUTPUT_DIR = 'analysis_output'

def find_latest_master_file(directory):
    """
    Automatically finds the newest master analysis file in the output folder.
    """
    # Pattern used by the analysis script
    pattern = "master_analysis_data_*.csv"
    
    # 1. Search in the analysis_output folder
    search_path = os.path.join(directory, pattern)
    files = glob.glob(search_path)
    
    # 2. Fallback: Search in the current directory (if script is run in sandbox)
    if not files:
        files = glob.glob(pattern)
        
    if not files:
        return None
        
    # Sort by creation time and return the latest
    return max(files, key=os.path.getctime)

# Auto-detect the file
INPUT_FILE = find_latest_master_file(ANALYSIS_OUTPUT_DIR)

# Styling Constants
CONDITION_ORDER = ['Baseline', 'HapticsFixed', 'HapticsAdaptive']
CONDITION_COLORS = {
    'Baseline': '#D3D3D3',
    'HapticsFixed': '#c1d4be',
    'HapticsAdaptive': '#bec1d4'
}
BASELINE_REF_COLOR = 'red'
DECIMAL_PLACES = 4

# Visualization Grid: (CSV_Column, Display_Title, Filename_Base)
METRIC_LAYOUT = {
    'row1': [
        ('CTE_Abs_mean', 'Lane Error (m)', 'Lane_Error'),
        ('CTE_Abs_std', 'SD of Lane Position', 'SDLP'),
        ('Heading_Abs_mean', 'Heading Error (°)', 'Heading_Error'),
        ('Heading_Abs_std', 'Heading Variability (°)', 'Heading_Variability'),
        ('Speed_mean', 'Average Speed (km/h)', 'Average_Speed'),
        ('LKA_SwitchOn_Time_Pct', 'System Usage (%)', 'System_Usage')
    ],
    'row2': [
        ('LKA_Switch_On_Count', 'Switch Activations', 'Switch_Activations'),
        ('HitRate', 'ST: Hit Rate (%)', 'ST_Hit_Rate'),
        ('FARate', 'ST: False Alarm Rate (%)', 'ST_False_Alarm_Rate'),
        ('CorrectedAcc', 'ST: Corrected Accuracy (%)', 'ST_Corrected_Accuracy'),
        ('Laptime', 'Lap Time (s)', 'Lap_Time'),
        ('n_curves', 'Detected Curves', 'Detected_Curves')
    ]
}

# ============================================================================
# STYLING & PLOTTING FUNCTIONS
# ============================================================================

def add_statistical_annotations(axis, data_values, condition_index):
    """Adds Mean, SD, and CV stats to the bottom of the plot."""
    if len(data_values) == 0: return
    
    mean_val = np.mean(data_values)
    std_val = np.std(data_values)
    cv_val = (std_val / mean_val) if mean_val != 0 else 0
    
    text = (f'M: {mean_val:.{DECIMAL_PLACES}f}\n'
            f'SD: {std_val:.{DECIMAL_PLACES}f}\n'
            f'CV: {cv_val:.{DECIMAL_PLACES}f}')
    
    axis.text(
        condition_index + 1, -0.06, text,
        transform=axis.get_xaxis_transform(),
        ha='center', va='top', fontsize=10, fontweight='bold',
        bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', pad=1),
        zorder=4
    )
    # Add Mean marker line
    axis.hlines(mean_val, condition_index + 0.75, condition_index + 1.25,
                colors='black', linestyles='--', linewidth=1.2, zorder=5)

def create_boxplot(axis, data, metric_col, title):
    """Generates the stylized boxplot with jittered dots."""
    plot_data = []
    for cond in CONDITION_ORDER:
        vals = data[data['Condition'] == cond][metric_col].dropna()
        plot_data.append(vals)
    
    bp = axis.boxplot(plot_data, labels=CONDITION_ORDER, patch_artist=True, widths=0.6,
                      medianprops=dict(color='black', linewidth=1.5), zorder=2)
    
    for patch, cond in zip(bp['boxes'], CONDITION_ORDER):
        patch.set_facecolor(CONDITION_COLORS[cond])
    
    for i, vals in enumerate(plot_data):
        if len(vals) > 0:
            x = np.random.normal(i + 1, 0.06, size=len(vals))
            axis.scatter(x, vals, alpha=0.5, s=30, color='black', edgecolors='white', zorder=3)
            add_statistical_annotations(axis, vals, i)
            
    # Red dashed line for Baseline Average
    baseline_mean = data[data['Condition'] == 'Baseline'][metric_col].mean()
    if not np.isnan(baseline_mean):
        axis.axhline(y=baseline_mean, color=BASELINE_REF_COLOR, ls='--', lw=1.5, alpha=0.8, zorder=1)
    
    axis.set_title(title, fontweight='bold', fontsize=18, pad=10)
    axis.grid(axis='y', linestyle=':', alpha=0.5)

# ============================================================================
# MAIN EXECUTION
# ============================================================================

def main():
    if not INPUT_FILE:
        print(f"Error: Could not find any analysis files in '{ANALYSIS_OUTPUT_DIR}'")
        return

    print(f"Reading latest analysis: {INPUT_FILE}")
    df = pd.read_csv(INPUT_FILE)

    fig, axes = plt.subplots(2, 6, figsize=(38, 25))

    for r_idx, row_key in enumerate(['row1', 'row2']):
        for c_idx, (col, title, _) in enumerate(METRIC_LAYOUT[row_key]):
            if col in df.columns:
                create_boxplot(axes[r_idx, c_idx], df, col, title)
            else:
                axes[r_idx, c_idx].text(0.5, 0.5, f"Column Not Found:\n{col}", ha='center')

    # Legend
    legend_elements = [
        Line2D([0], [0], color='black', lw=1.5, label='Median'),
        Line2D([0], [0], color='black', lw=1.2, ls='--', label='Mean'),
        Line2D([0], [0], color=BASELINE_REF_COLOR, lw=1.2, ls='--', label='Baseline Reference'),
        Patch(facecolor='#D3D3D3', label='Baseline'),
        Patch(facecolor='#c1d4be', label='Fixed Haptics'),
        Patch(facecolor='#bec1d4', label='Adaptive Haptics')
    ]
    fig.legend(handles=legend_elements, loc='upper left', bbox_to_anchor=(0.01, 0.98),
               ncol=1, fontsize=14, frameon=True, framealpha=0.9, edgecolor='black')

    plt.suptitle('Haptic Intervention: Usage, Trust & Performance Analysis', 
                 fontsize=32, fontweight='bold', y=0.98)
    plt.subplots_adjust(left=0.08, bottom=0.12, right=0.95, top=0.92, hspace=0.4, wspace=0.25)

    output_path = 'haptics_master_report.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Done! Report saved as: {output_path}")
    plt.show()

if __name__ == "__main__":
    main()